### ISSUE TITLE
Hover

### ISSUE THREAD

**Issue by philyboysmith** [eschmar/crosshair.js#1]
Can you simultaneously use crosshair and detect either :hover events in css or onmouseover events in js? I'm struggling to detect this

**Comment by eschmar** [comment]
Mmh.. yes, that should work. Did you see, that the crosshair'ed element is wrapped in a `.crosshair` div? For example, pasting the following snippet on the [project page](http://eschmar.github.io/crosshair.js/) into the console works for me:

``` js
$('#demo-img').on('mouseover', function(){console.log('pew');});
```

Do you mean this? Or do you have an example?

**Comment by philyboysmith** [comment]
Hmmm, what I'm trying to do works perfectly on your demo something to do with my local setup, possibly caused by the contents being dynamically loaded. Closing this issue as whatever the problem is, it's not at your end...
