### ISSUE TITLE
Zoom - Get Coordinates from larger Image

### ISSUE THREAD

**Issue by grubbychicken** [eschmar/crosshair.js#2]
Hi eschmar,

Thanks for the plugin! It's great.

Im using it to allow my users to select a pixel from an image.  But I'm struggling with one thing, and I hope you can help!

I have a large image ~2800px x 1900px that is scaled down to 945px x 630px and I am trying to allow my users to select a specific pixel from the large image.

As you have suggested, I used the percentage  to calculate this, but I'm unable to to select an exact pixel as when I move the crosshair by 1px the coordinates change by 3px.  This is obviously to do with the scaling.  

I was wondering if you could help me extend your plugin to include some kind of magnify so the user is able to select an exact pixel from the large image.

Thanks in advance for your help!

**Comment by eschmar** [comment]
Hej grubbychicken,

thanks for your post and sorry for the late answer, was quite busy. Have you found a solution to your problem? 

As you correctly reasoned, you will have to use an unscaled version of the image to make this plugin work per pixel. Or you somehow magnify (zoom in) the image further. One possible way would be to use the callback function to replace the current image with a zoomed in version, should the current image scaled. Then the user could choose a pixel once again, this time in unscaled or even zoomed in version of the image.

Let me know if the issue still persists.

Cheers,
eschmar
